version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Familia_282679
      MYSQL_DATABASE: OrganizaTest
      MYSQL_USER: root
      MYSQL_PASSWORD: Familia_282679
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
